spring.application.name=Fintrack
server.port=8081

#spring.datasource.url=${DATASOURCE_URL}
#spring.datasource.username=${DATASOURCE_USER}
#spring.datasource.password=${DATASOURCE_PASSWORD}
#frontend.url=${FRONTEND_URL}

spring.datasource.url=jdbc:postgresql://localhost:5432/fintrack
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update



#security.jwt.secret=${SECURITY_JWT_SECRET}
security.jwt.expiration-ms=900000
security.jwtRefreshExpirationMs=604800000

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m

spring.jpa.show-sql=true

#spring.mail.host=${SPRING_MAIL_HOST}
#spring.mail.port=${SPRING_MAIL_PORT}
#spring.mail.username=${SPRING_MAIL_USERNAME}
#spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/manage-fintrack
